version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.4

    working_directory: /go/src/github.com/helloeave/murphy

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: rm -Rf /go/src/github.com/satori/go.uuid
      - run: mkdir /go/src/github.com/satori/go.uuid
      - run: curl https://raw.githubusercontent.com/satori/go.uuid/b061729afc07e77a8aa4fad0a2fd840958f1942a/uuid.go > /go/src/github.com/satori/go.uuid/uuid.go
      - run: go test -v ./...
